import type { HostawayReviewRaw } from "./types"

export const mockReviews: HostawayReviewRaw[] = [
  {
    id: 7453,
    type: "host-to-guest",
    status: "published",
    rating: null,
    publicReview: "Shane and family are wonderful! Would definitely host again :)",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2024-01-15 22:45:14",
    guestName: "Shane Finkelstein",
    listingName: "2B N1 A - 29 Shoreditch Heights",
  },
  {
    id: 7454,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Beautiful apartment with great amenities. Host was very responsive.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 8 },
      { category: "location", rating: 9 },
    ],
    submittedAt: "2024-01-20 10:30:00",
    guestName: "Maria Garcia",
    listingName: "2B N1 A - 29 Shoreditch Heights",
  },
  {
    id: 7455,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Excellent stay! Everything was clean and well-maintained.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 8 },
    ],
    submittedAt: "2024-02-01 14:20:30",
    guestName: "John Smith",
    listingName: "1B Luxury Suite - Chelsea District",
  },
  {
    id: 7456,
    type: "host-to-guest",
    status: "published",
    rating: null,
    publicReview: "Great guests, left the place in perfect condition.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
      { category: "communication", rating: 9 },
    ],
    submittedAt: "2024-02-05 09:15:00",
    guestName: "Emma Wilson",
    listingName: "1B Luxury Suite - Chelsea District",
  },
  {
    id: 7457,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Good location but apartment was a bit smaller than expected.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "accuracy", rating: 6 },
      { category: "location", rating: 9 },
      { category: "communication", rating: 8 },
    ],
    submittedAt: "2024-02-10 16:45:20",
    guestName: "David Chen",
    listingName: "2B N1 A - 29 Shoreditch Heights",
  },
  {
    id: 7458,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Perfect for a weekend getaway. Highly recommend!",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 9 },
      { category: "location", rating: 9 },
    ],
    submittedAt: "2024-02-15 11:20:00",
    guestName: "Sophie Martin",
    listingName: "3B Penthouse - Downtown",
  },
  {
    id: 7459,
    type: "host-to-guest",
    status: "published",
    rating: null,
    publicReview: "Excellent guests! Very respectful of the property.",
    reviewCategory: [
      { category: "respect_house_rules", rating: 10 },
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 9 },
    ],
    submittedAt: "2024-02-20 13:00:00",
    guestName: "James Johnson",
    listingName: "3B Penthouse - Downtown",
  },
  {
    id: 7460,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Comfortable stay but WiFi could be better.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 7 },
      { category: "accuracy", rating: 8 },
      { category: "location", rating: 8 },
    ],
    submittedAt: "2024-02-25 15:30:00",
    guestName: "Lisa Anderson",
    listingName: "1B Luxury Suite - Chelsea District",
  },
  {
    id: 7461,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Outstanding! Best stay in the city!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
    ],
    submittedAt: "2024-03-01 10:00:00",
    guestName: "Robert Brown",
    listingName: "2B N1 A - 29 Shoreditch Heights",
  },
]
